### ISSUE TITLE
library(CannaBarcode)

### ISSUE THREAD

**Issue by omarbenites** [CannaData/CannaBarcode#3]
Hi CannaData, 
First, thanks for your nice library for barcodes in R, it looks good!.  While I was reading your examples for Shiny (in the README file), and I found some troubleshootings because you include a library `CannaBarcode` that apparentely does not exist. So, basically I change `CannaBarcode` for `ShinyBarcode`.

### Before modifications (README file)

```
library(shiny)
library(CannaBarcode)

ui <- fluidPage(
  # must include javascript dependencies
  CannaBarcode::includeJsBarcode(cdn = TRUE),
  numericInput("value", "Input a positive integer", 8675309, 0, 1000000),
  CannaBarcode::barcodeOutput("barcode")
)

server <- function(input, output, session) {
  output$barcode <- CannaBarcode::renderBarcode(
    input$value
  )
}

shinyApp(ui = ui, server = server)
```

### After modifications

```
library(shiny)
library(shinyBarcode)
ui <- fluidPage(
  # must include javascript dependencies
  shinyBarcode::includeJsBarcode(cdn = TRUE),
  numericInput("value", "Input a positive integer", 8675309, 0, 1000000),
  shinyBarcode::barcodeOutput("barcode")
)

server <- function(input, output, session) {
  output$barcode <- shinyBarcode::renderBarcode(
    input$value
  )
}

shinyApp(ui = ui, server = server)
```

That's all, and keep it up your good work :+1:

**Comment by carlganz** [comment]
Thanks!

FWIW this repo is mostly deprecated. I use [zintr](https://github.com/CannaData/zintr) for generating barcodes in R.

**Comment by omarbenites** [comment]
And Does it integrated with Shiny also?
Cheers.
